# type: ignore
"""add_memory_bullets

Revision ID: 9c4e1b7a6d2f
Revises: f1g2h3i4j5k6
Create Date: 2025-12-22 14:45:00.000000+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "9c4e1b7a6d2f"
down_revision = "f1g2h3i4j5k6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "memory",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("is_global", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("section", sa.String(length=255), nullable=False),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("harmful_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(is_global IS TRUE AND user_id IS NULL) OR (is_global IS FALSE AND user_id IS NOT NULL)",
            name=op.f("ck_memory_global_user"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_memory_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory")),
    )
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_is_global"), ["is_global"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_user_id"), ["user_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_section"), ["section"], unique=False)

    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.create_table_comment(
            "Memory bullets for agent context",
            existing_comment=None,
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.drop_table_comment(existing_comment="Memory bullets for agent context")

    with op.batch_alter_table("memory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_section"))
        batch_op.drop_index(batch_op.f("ix_memory_user_id"))
        batch_op.drop_index(batch_op.f("ix_memory_is_global"))

    op.drop_table("memory")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
