# type: ignore
"""add todo series

Revision ID: 17ca2745828b
Revises: 9c4e1b7a6d2f
Create Date: 2026-02-01 00:00:00.000000+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "17ca2745828b"
down_revision = "9c4e1b7a6d2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todo_series",
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "rule_type",
            sa.Enum("daily", "weekly", "monthly", "interval", name="todo_series_rule_type_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("rule_payload", postgresql.JSONB(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("default_start_time", sa.Time(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_todo_series_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_todo_series")),
    )
    with op.batch_alter_table("todo_series", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_todo_series_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("todo_series", schema=None) as batch_op:
        batch_op.create_table_comment(
            "Recurring todo series",
            existing_comment=None,
        )

    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("series_id", sa.GUID(length=16), nullable=True))
        batch_op.create_index(batch_op.f("ix_todo_series_id"), ["series_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_todo_series_id_todo_series"),
            "todo_series",
            ["series_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todo", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_todo_series_id_todo_series"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_todo_series_id"))
        batch_op.drop_column("series_id")

    with op.batch_alter_table("todo_series", schema=None) as batch_op:
        batch_op.drop_table_comment(existing_comment="Recurring todo series")

    with op.batch_alter_table("todo_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_todo_series_user_id"))

    op.drop_table("todo_series")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
